/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellAttendanceRouteImport } from './routes/_shell/attendance'
import { Route as ShellAuditLogRouteImport } from './routes/_shell/audit-log'
import { Route as ShellClassesRouteImport } from './routes/_shell/classes'
import { Route as ShellDashboardRouteImport } from './routes/_shell/dashboard'
import { Route as ShellFinanceRouteImport } from './routes/_shell/finance'
import { Route as ShellIdCardsRouteImport } from './routes/_shell/id-cards'
import { Route as ShellLibraryRouteImport } from './routes/_shell/library'
import { Route as ShellReportsRouteImport } from './routes/_shell/reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellSubjectsRouteImport } from './routes/_shell/subjects'
import { Route as ShellTeachersRouteImport } from './routes/_shell/teachers'
import { Route as ShellTranscriptsRouteImport } from './routes/_shell/transcripts'
import { Route as ShellVisitorsRouteImport } from './routes/_shell/visitors'
import { Route as ShellResultsIndexRouteImport } from './routes/_shell/results/index'
import { Route as ShellResultsEntryRouteImport } from './routes/_shell/results/entry'
import { Route as ShellStudentsIndexRouteImport } from './routes/_shell/students/index'
import { Route as ShellStudentsStudentIdRouteImport } from './routes/_shell/students/$studentId'
import { Route as ShellResultsStudentIdReportRouteImport } from './routes/_shell/results/$studentId/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAttendanceRoute = ShellAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditLogRoute = ShellAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClassesRoute = ShellClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFinanceRoute = ShellFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIdCardsRoute = ShellIdCardsRouteImport.update({
  id: '/id-cards',
  path: '/id-cards',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSubjectsRoute = ShellSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTeachersRoute = ShellTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTranscriptsRoute = ShellTranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVisitorsRoute = ShellVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResultsIndexRoute = ShellResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResultsEntryRoute = ShellResultsEntryRouteImport.update({
  id: '/results/entry',
  path: '/results/entry',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudentsIndexRoute = ShellStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudentsStudentIdRoute = ShellStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResultsStudentIdReportRoute =
  ShellResultsStudentIdReportRouteImport.update({
    id: '/results/$studentId/report',
    path: '/results/$studentId/report',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof ShellAttendanceRoute
  '/audit-log': typeof ShellAuditLogRoute
  '/classes': typeof ShellClassesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/finance': typeof ShellFinanceRoute
  '/id-cards': typeof ShellIdCardsRoute
  '/library': typeof ShellLibraryRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/subjects': typeof ShellSubjectsRoute
  '/teachers': typeof ShellTeachersRoute
  '/transcripts': typeof ShellTranscriptsRoute
  '/visitors': typeof ShellVisitorsRoute
  '/results/entry': typeof ShellResultsEntryRoute
  '/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/results/': typeof ShellResultsIndexRoute
  '/students/': typeof ShellStudentsIndexRoute
  '/results/$studentId/report': typeof ShellResultsStudentIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof ShellAttendanceRoute
  '/audit-log': typeof ShellAuditLogRoute
  '/classes': typeof ShellClassesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/finance': typeof ShellFinanceRoute
  '/id-cards': typeof ShellIdCardsRoute
  '/library': typeof ShellLibraryRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/subjects': typeof ShellSubjectsRoute
  '/teachers': typeof ShellTeachersRoute
  '/transcripts': typeof ShellTranscriptsRoute
  '/visitors': typeof ShellVisitorsRoute
  '/results/entry': typeof ShellResultsEntryRoute
  '/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/results': typeof ShellResultsIndexRoute
  '/students': typeof ShellStudentsIndexRoute
  '/results/$studentId/report': typeof ShellResultsStudentIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/attendance': typeof ShellAttendanceRoute
  '/_shell/audit-log': typeof ShellAuditLogRoute
  '/_shell/classes': typeof ShellClassesRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/finance': typeof ShellFinanceRoute
  '/_shell/id-cards': typeof ShellIdCardsRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/subjects': typeof ShellSubjectsRoute
  '/_shell/teachers': typeof ShellTeachersRoute
  '/_shell/transcripts': typeof ShellTranscriptsRoute
  '/_shell/visitors': typeof ShellVisitorsRoute
  '/_shell/results/entry': typeof ShellResultsEntryRoute
  '/_shell/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/_shell/results/': typeof ShellResultsIndexRoute
  '/_shell/students/': typeof ShellStudentsIndexRoute
  '/_shell/results/$studentId/report': typeof ShellResultsStudentIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/audit-log'
    | '/classes'
    | '/dashboard'
    | '/finance'
    | '/id-cards'
    | '/library'
    | '/reports'
    | '/settings'
    | '/subjects'
    | '/teachers'
    | '/transcripts'
    | '/visitors'
    | '/results/entry'
    | '/students/$studentId'
    | '/results/'
    | '/students/'
    | '/results/$studentId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/attendance'
    | '/audit-log'
    | '/classes'
    | '/dashboard'
    | '/finance'
    | '/id-cards'
    | '/library'
    | '/reports'
    | '/settings'
    | '/subjects'
    | '/teachers'
    | '/transcripts'
    | '/visitors'
    | '/results/entry'
    | '/students/$studentId'
    | '/results'
    | '/students'
    | '/results/$studentId/report'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/attendance'
    | '/_shell/audit-log'
    | '/_shell/classes'
    | '/_shell/dashboard'
    | '/_shell/finance'
    | '/_shell/id-cards'
    | '/_shell/library'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/subjects'
    | '/_shell/teachers'
    | '/_shell/transcripts'
    | '/_shell/visitors'
    | '/_shell/results/entry'
    | '/_shell/students/$studentId'
    | '/_shell/results/'
    | '/_shell/students/'
    | '/_shell/results/$studentId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/attendance': {
      id: '/_shell/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof ShellAttendanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit-log': {
      id: '/_shell/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof ShellAuditLogRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/classes': {
      id: '/_shell/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ShellClassesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/finance': {
      id: '/_shell/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof ShellFinanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/id-cards': {
      id: '/_shell/id-cards'
      path: '/id-cards'
      fullPath: '/id-cards'
      preLoaderRoute: typeof ShellIdCardsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/subjects': {
      id: '/_shell/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof ShellSubjectsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/teachers': {
      id: '/_shell/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof ShellTeachersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/transcripts': {
      id: '/_shell/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof ShellTranscriptsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/visitors': {
      id: '/_shell/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof ShellVisitorsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/results/': {
      id: '/_shell/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ShellResultsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/results/entry': {
      id: '/_shell/results/entry'
      path: '/results/entry'
      fullPath: '/results/entry'
      preLoaderRoute: typeof ShellResultsEntryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/students/': {
      id: '/_shell/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof ShellStudentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/students/$studentId': {
      id: '/_shell/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof ShellStudentsStudentIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/results/$studentId/report': {
      id: '/_shell/results/$studentId/report'
      path: '/results/$studentId/report'
      fullPath: '/results/$studentId/report'
      preLoaderRoute: typeof ShellResultsStudentIdReportRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAttendanceRoute: typeof ShellAttendanceRoute
  ShellAuditLogRoute: typeof ShellAuditLogRoute
  ShellClassesRoute: typeof ShellClassesRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFinanceRoute: typeof ShellFinanceRoute
  ShellIdCardsRoute: typeof ShellIdCardsRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellSubjectsRoute: typeof ShellSubjectsRoute
  ShellTeachersRoute: typeof ShellTeachersRoute
  ShellTranscriptsRoute: typeof ShellTranscriptsRoute
  ShellVisitorsRoute: typeof ShellVisitorsRoute
  ShellResultsEntryRoute: typeof ShellResultsEntryRoute
  ShellStudentsStudentIdRoute: typeof ShellStudentsStudentIdRoute
  ShellResultsIndexRoute: typeof ShellResultsIndexRoute
  ShellStudentsIndexRoute: typeof ShellStudentsIndexRoute
  ShellResultsStudentIdReportRoute: typeof ShellResultsStudentIdReportRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAttendanceRoute: ShellAttendanceRoute,
  ShellAuditLogRoute: ShellAuditLogRoute,
  ShellClassesRoute: ShellClassesRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFinanceRoute: ShellFinanceRoute,
  ShellIdCardsRoute: ShellIdCardsRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellSubjectsRoute: ShellSubjectsRoute,
  ShellTeachersRoute: ShellTeachersRoute,
  ShellTranscriptsRoute: ShellTranscriptsRoute,
  ShellVisitorsRoute: ShellVisitorsRoute,
  ShellResultsEntryRoute: ShellResultsEntryRoute,
  ShellStudentsStudentIdRoute: ShellStudentsStudentIdRoute,
  ShellResultsIndexRoute: ShellResultsIndexRoute,
  ShellStudentsIndexRoute: ShellStudentsIndexRoute,
  ShellResultsStudentIdReportRoute: ShellResultsStudentIdReportRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
