/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellClassesRouteImport } from './routes/_shell/classes'
import { Route as ShellDashboardRouteImport } from './routes/_shell/dashboard'
import { Route as ShellTeachersRouteImport } from './routes/_shell/teachers'
import { Route as ShellStudentsIndexRouteImport } from './routes/_shell/students/index'
import { Route as ShellStudentsStudentIdRouteImport } from './routes/_shell/students/$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellClassesRoute = ShellClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTeachersRoute = ShellTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudentsIndexRoute = ShellStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudentsStudentIdRoute = ShellStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/classes': typeof ShellClassesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/teachers': typeof ShellTeachersRoute
  '/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/students/': typeof ShellStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/classes': typeof ShellClassesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/teachers': typeof ShellTeachersRoute
  '/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/students': typeof ShellStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/classes': typeof ShellClassesRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/teachers': typeof ShellTeachersRoute
  '/_shell/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/_shell/students/': typeof ShellStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/classes'
    | '/dashboard'
    | '/teachers'
    | '/students/$studentId'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/classes'
    | '/dashboard'
    | '/teachers'
    | '/students/$studentId'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/classes'
    | '/_shell/dashboard'
    | '/_shell/teachers'
    | '/_shell/students/$studentId'
    | '/_shell/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/classes': {
      id: '/_shell/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ShellClassesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/teachers': {
      id: '/_shell/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof ShellTeachersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/students/': {
      id: '/_shell/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof ShellStudentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/students/$studentId': {
      id: '/_shell/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof ShellStudentsStudentIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellClassesRoute: typeof ShellClassesRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellTeachersRoute: typeof ShellTeachersRoute
  ShellStudentsStudentIdRoute: typeof ShellStudentsStudentIdRoute
  ShellStudentsIndexRoute: typeof ShellStudentsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellClassesRoute: ShellClassesRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellTeachersRoute: ShellTeachersRoute,
  ShellStudentsStudentIdRoute: ShellStudentsStudentIdRoute,
  ShellStudentsIndexRoute: ShellStudentsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
